- id: clang-format2
  name: clang-format2
  entry: clang-format2
  language: system
  files: \.(cu|hpp|cuh|h|cpp|c)
  args: ["-i","-style=Google"]
  require_serial: false
  additional_dependencies: []
